### ISSUE TITLE
writeMicroseconds is not supported

### ISSUE THREAD

**Issue by dtex** [adafruit/Adafruit_TiCoServo#3]
- Arduino board: **All**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **All**

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):  **Call servo.writeMicroseconds() and observe that nothing happens**

Would y'all accept a PR that adds this method?

**Comment by ladyada** [comment]
hmm? what exact board/IDE did you test with?

**Comment by chris-m-brown** [comment]
Hey ladyada, I submitted the original issue and I am using an arduino mega 2560 (v1.8.9) with configurableFirmata and johnny-five.

**Comment by ladyada** [comment]
ok regarding your note "Arduino board: All" above, did you test with an UNO / 328p or *only* the mega?

**Comment by chris-m-brown** [comment]
Only the mega.

**Comment by ladyada** [comment]
ok thanks for clarifying. we'll take a PR as long as you also test and verify it continues to work on the 328p :)

**Comment by dtex** [comment]
@kriztupher1 I see that I overlooked the writeMicroseconds implementation that is already in the code here so something else is going on. Could be something specific to the way firmata is calling the method, I'm not sure. I'll see if I can set up something to test with later tonight.

**Comment by chris-m-brown** [comment]
Any help would be appreciated on this, Donovan. I have spent 2 days trying to figure it out. I’ll be in your debt if you can solve it.

**Comment by dtex** [comment]
Let's close this and bounce back over the the Johnny-Five repo until we're sure of where the issue is.
